Fixed compilation errors due to changing a function name without updating the calls.
git-svn-id: https://dev.chiasoft.net:8443/svn/svn_vana/trunk@937 23f3cdc0-e6d1-42be-a0c1-51f4125517bb